### ISSUE TITLE
Create random sort URL

### ISSUE THREAD

**Issue by Xeoncross** [relrod/dagd#12]
You should be creating the random URL based on the ID of the record. Otherwise you might be doing randstr() a **lot** later on just trying to find a non-used string.

    $fromBase = 10;
    $toBase = 36;
    print base_convert($number, $fromBase, $toBase). "\n";
    print base_convert(base_convert($number, $fromBase, $toBase), $toBase, $fromBase);

**Comment by relrod** [comment]
Going to close this for now (a few years later) - if we run into issues down the road we can revisit. I don't particularly want to create predictable shorturls.
