### ISSUE TITLE
Usage quota, if any

### ISSUE THREAD

**Issue by impredicative** [relrod/dagd#47]
Thanks for this service. Is there a usage limit? I want to shorten up to 500 news URLs per hour from a single IP. Would this be okay?

**Comment by relrod** [comment]
You can try 16 concurrent connections, sure. Largely, I think any legitimate performance issue you run into is something we'd want to fix anyway, even if it means we need to throw more hardware at the site.

I'll keep an eye on the graphs and alerts over the next few days, but I think things should be just fine. I do appreciate you asking!

**Comment by relrod** [comment]
Yeah setting a descriptive user agent could be useful for filtering and so on. Not strictly necessary but it wouldn't hurt and could end up being useful. Ultimately it's up to you though :)
