### ISSUE TITLE
Accept bitcoin donations

### ISSUE THREAD

**Issue by impredicative** [relrod/dagd#48]
It shouldn't hurt to accept donations via a crypto such as bitcoin. This allows people to donate more anonymously.

It is easy to setup a cold wallet using a dedicated laptop booting it with Tails OS liveUSB as it has Electrum over Tor. Its documentation covers it reasonably. Other people use a hardware wallet. If you switch to accepting it, please ensure that at least one other person you trust can fully access it.

There is no rush. I have nothing in mind for a few months w.r.t. this issue.

**Comment by relrod** [comment]
Thanks - it's something I'll think on. I think it would be easy enough to create a coinbase account to accept bitcoin donations. I appreciate you considering donating! It means a lot. :slightly_smiling_face:
