### ISSUE TITLE
Reference Python code for shortening a long URL

### ISSUE THREAD

**Issue by impredicative** [relrod/dagd#49]
I am documenting here the most basic Python reference code for shortening a long URL as per the [API](https://da.gd/help#shorten):

```python
> import requests
> response = requests.post('https://da.gd/s/', data={'url': 'https://realpython.com/python-requests/'}, timeout=3)
> response.raise_for_status()
> response.status_code
200
> response.text
'https://da.gd/KFUPh\n'
> response.text.rstrip()
'https://da.gd/KFUPh'
```

**Comment by relrod** [comment]
FWIW if you use `https://da.gd/s?strip` instead (or send it in the payload like `'strip': True`), it'll drop the trailing newline from the response and you won't have to do it in Python.
