### ISSUE TITLE
Long URL is not a valid URL

### ISSUE THREAD

**Issue by impredicative** [relrod/dagd#51]
I am receiving the error "Long URL is not a valid URL" for the following long URL:

https://www.investing.com/central-banks/european-central-bank/speeches/european-banking-supervision-–-business-model-analysis-200142286

Note that the quoted version of the same long URL below encounters no such error:

https://www.investing.com/central-banks/european-central-bank/speeches/european-banking-supervision-%E2%80%93-business-model-analysis-200142286

The character in question is EN DASH, but other non-ASCII characters can similarly come up in other examples.

Can dagd just work with the given unicode URL without me having to quote it? Is dagd too strict in checking URL validity?

**Comment by relrod** [comment]
I think you should urlencode before sending the URL to dagd. I think we're following [the spec](http://www.faqs.org/rfcs/rfc1738.html) correctly here?

>   Thus, only alphanumerics, the special characters "$-_.+!*'(),", and
>   reserved characters used for their reserved purposes may be used
>   unencoded within a URL.

**Comment by relrod** [comment]
Ultimately we use `filter_var()` and `FILTER_VALIDATE_URL` to do that validation.
